version: '3'
services:
  mysqldb:
      container_name: mysqldb
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: unless-stopped
      volumes:
        - $HOME/database:/var/lib/mysql
      ports:
        - 3306:3306
      expose:
        - 3306
      environment:
        MYSQL_DATABASE: user-management
        MYSQL-USER: admin
        MYSQL-PASSWORD: passwordtest
        MYSQL_ROOT_PASSWORD: passwordtest
        SERVICE_TAGS: prod
        SERVICE_NAME: mysqldb
      networks:
        - internalnet
  
  

networks:
  internalnet:
    driver: bridge
